workspace:
  base: /go
  path: src/github.com/deis/prow
pipeline:
  test:
    image: golang:1.8.0
    commands:
      - go get github.com/Masterminds/glide
      - make bootstrap test
  dist-canary:
    image: golang:1.8.0
    commands:
      - make build-cross docker-binary
      - VERSION=${DRONE_COMMIT} make dist checksum
      - VERSION=canary make dist checksum
    when:
      branch: master
      event: push
  dist-release:
    image: golang:1.8.0
    commands:
      - make build-cross docker-binary
      - VERSION=${DRONE_TAG} make dist checksum
    when:
      event: tag
  dist-upload:
    image: plugins/s3
    acl: public-read
    region: us-west-2
    bucket: deis-prow
    access_key: ${AWS_ACCESS_KEY_ID}
    secret_key: ${AWS_SECRET_ACCESS_KEY}
    source: _dist/*
    strip_prefix: _dist/
    target: /
    when:
      branch: master
      event: [push, tag]
  docker-canary:
    image: plugins/docker
    repo: quay.io/deis/prowd
    registry: quay.io
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    tag:
      - canary
    when:
      branch: master
      event: push
  docker-release:
    image: plugins/docker
    repo: quay.io/deis/prowd
    registry: quay.io
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    tag:
      - ${DRONE_TAG}
    when:
      event: tag
