[[constraint]]
  name = "github.com/Azure/azure-storage-blob-go"
  branch = "master"

[[constraint]]
  name = "github.com/Masterminds/vcs"
  version = "1.11.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.4"

[[constraint]]
  name = "github.com/docker/docker"
  source = "https://github.com/moby/moby"
  revision = "ae7016427f8cba4e4d8fcb979d6ba313ee2c0702"

[[constraint]]
  name = "github.com/docker/cli"
  revision = "37eebe5cb6eff08bde94d17111caa8fc099d7a94"

[[override]]
  name = "github.com/docker/distribution"
  revision = "a97d7c0c155be14d1380c075d3197a5d89c2abc2"

[[constraint]]
  name = "k8s.io/helm"
  version = "~v2.9.0"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "github.com/fsnotify/fsnotify"
  version = "1.2.1"

[[override]]
  name = "k8s.io/kubernetes"
  branch = "release-1.10"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.0"

[[override]]
  name = "k8s.io/api"
  branch = "release-1.10"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.10"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.10"

[[override]]
  name = "github.com/imdario/mergo"
  revision = "6633656539c1639d9d78127b7d47c622b5d7b6dc"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.4-2-g300106c"

[[override]]
  name = "google.golang.org/grpc"
  version = "1.7.2"

[[constraint]]
  name = "github.com/jbrukh/bayesian"
  branch = "master"
