apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: draft
        name: draftd
    spec:
      containers:
      - name: draftd
        image: "{{ .Values.image.registry }}/{{ .Values.image.org }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - start
        - --registry-url={{ .Values.registry.url }}
        - --registry-org={{ .Values.registry.org }}
        - --registry-auth={{ .Values.registry.authtoken }}
        {{- if .Values.debug }}
        - --debug
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.http.internalPort }}
        env:
        - name: DRAFT_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.service.http.internalPort }}
        readinessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.service.http.internalPort }}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
