apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: prow
        name: prowd
    spec:
      containers:
      - name: prowd
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - start
        {{- if .Values.debug }}
        - --debug
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.http.internalPort }}
        livenessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.service.http.internalPort }}
        readinessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.service.http.internalPort }}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
        env:
          - name: "REGISTRY_SERVICE_PORT"
            value: "{{ .Values.service.registry.externalPort }}"
      - name: registry
        image: registry:2
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.service.registry.internalPort }}
          hostPort: {{ .Values.service.registry.externalPort }}
          name: registry
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
