# Default values for python.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  registry: docker.io
  org: microsoft
  name: aspnetcore-build
  tag: 1.1
  pullPolicy: IfNotPresent
service:
  name: dotnetcore
  type: ClusterIP
  externalPort: 8080
  internalPort: 80
resources:
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi
