apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prowd
  labels:
    chart: "prowd-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: prow
        name: prowd
    spec:
      containers:
      - name: prowd
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - start
        ports:
        - containerPort: 44135
        livenessProbe:
          httpGet:
            path: /ping
            port: 44135
        readinessProbe:
          httpGet:
            path: /ping
            port: 44135
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
      - name: registry
        image: registry:2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          hostPort: 5000
          name: registry
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
