apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 44135
    - name: registry
      port: 5000
      targetPort: 5000
  selector:
    app: {{ .Chart.Name }}
