apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.http.externalPort }}
      targetPort: {{ .Values.service.http.internalPort }}
  selector:
    app: {{ .Chart.Name }}
