apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    helm.sh/chart: {{ template "chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
