apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: draft
        name: draftd
    spec:
      containers:
      - name: draftd
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - start
        - --registry-url={{ .Values.registry.url }}
        - --registry-auth={{ .Values.registry.authtoken }}
        {{- if .Values.debug }}
        - --debug
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.http.internalPort }}
        env:
        - name: DRAFT_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
      - name: dind
        image: docker:17.05.0-ce-dind
        args:
        - --insecure-registry=10.96.0.0/12
        - --insecure-registry=10.0.0.0/24
        env:
        - name: DOCKER_DRIVER
          value: overlay
        securityContext:
            privileged: true
        volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
      volumes:
      - name: docker-graph-storage
        emptyDir: {}
      nodeSelector:
        beta.kubernetes.io/os: linux
