# Default values for lein projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  name: clojure
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
resources:
  limits:
    cpu: 1000m
    memory: 128Mi
  requests:
    cpu: 1000m
    memory: 128Mi
ingress:
  enabled: false
